---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.2" 
notifications:
  email:
    - julioguevara150@gmail.com
